export const countries = [
  {
    name: "United States",
    flag: "🇺🇸",
    rating: 4.8,
    description:
      "Home to world-renowned universities like Harvard, MIT, and Stanford.",
    visaType: "F-1 Student Visa",
    workRights: "CPT/OPT available",
    avgTuition: "$50,000/year",
    livingCost: "$15,000/year",
    isEnglishSpeaking: true,
    isLowCost: false,
    hasWorkRights: true,
  },
  {
    name: "United Kingdom",
    flag: "🇬🇧",
    rating: 4.7,
    description:
      "Rich academic tradition with universities like Oxford and Cambridge.",
    visaType: "Student Visa",
    workRights: "20 hours/week",
    avgTuition: "£25,000/year",
    livingCost: "£12,000/year",
    isEnglishSpeaking: true,
    isLowCost: false,
    hasWorkRights: true,
  },
  {
    name: "Canada",
    flag: "🇨🇦",
    rating: 4.6,
    description:
      "Welcoming immigration policies and high-quality education system.",
    visaType: "Study Permit",
    workRights: "20 hours/week",
    avgTuition: "C$30,000/year",
    livingCost: "C$15,000/year",
    isEnglishSpeaking: true,
    isLowCost: false,
    hasWorkRights: true,
  },
  {
    name: "Germany",
    flag: "🇩🇪",
    rating: 4.5,
    description:
      "Free tuition at public universities and strong engineering programs.",
    visaType: "Student Visa",
    workRights: "20 hours/week",
    avgTuition: "€0/year",
    livingCost: "€8,000/year",
    isEnglishSpeaking: false,
    isLowCost: true,
    hasWorkRights: true,
  },
  {
    name: "Australia",
    flag: "🇦🇺",
    rating: 4.4,
    description:
      "High-quality education and post-study work opportunities.",
    visaType: "Student Visa",
    workRights: "20 hours/week",
    avgTuition: "A$35,000/year",
    livingCost: "A$18,000/year",
    isEnglishSpeaking: true,
    isLowCost: false,
    hasWorkRights: true,
  },
  {
    name: "Netherlands",
    flag: "🇳🇱",
    rating: 4.3,
    description:
      "English-taught programs and excellent research opportunities.",
    visaType: "Student Visa",
    workRights: "16 hours/week",
    avgTuition: "€15,000/year",
    livingCost: "€10,000/year",
    isEnglishSpeaking: true,
    isLowCost: true,
    hasWorkRights: true,
  },
];