export interface Training {
  id: number;
  title: string;
  instructor: string;
  duration: string;
  level: "Beginner" | "Intermediate" | "Advanced" | "All Levels";
  rating: number;
  students: number;
  price: string;
  description: string;
  topics: string[];
  nextStart: string;
  image: string;
  category: string;
  isLive: boolean;
  language: string;
  certificate: boolean;
}

export const trainings: Training[] = [
  // Test Preparation Courses
  {
    id: 1,
    title: "SAT Math Mastery",
    instructor: "Dr. Sarah Johnson",
    duration: "8 weeks",
    level: "Intermediate",
    rating: 4.8,
    students: 1250,
    price: "$199",
    description: "Master all SAT Math concepts with comprehensive practice and expert guidance.",
    topics: ["Algebra", "Geometry", "Trigonometry", "Data Analysis", "Problem Solving"],
    nextStart: "Dec 15, 2024",
    image: "/sat-math-course.jpg",
    category: "Test Prep",
    isLive: true,
    language: "English",
    certificate: true,
  },
  {
    id: 2,
    title: "TOEFL Speaking Excellence",
    instructor: "Prof. Michael Chen",
    duration: "6 weeks",
    level: "All Levels",
    rating: 4.9,
    students: 890,
    price: "$149",
    description: "Improve your TOEFL speaking skills with structured practice and feedback.",
    topics: ["Speaking Fluency", "Pronunciation", "Task Response", "Time Management", "Confidence Building"],
    nextStart: "Dec 20, 2024",
    image: "/toefl-speaking-course.jpg",
    category: "Test Prep",
    isLive: true,
    language: "English",
    certificate: true,
  },
  {
    id: 3,
    title: "IELTS Writing Masterclass",
    instructor: "Dr. Emma Thompson",
    duration: "5 weeks",
    level: "Intermediate",
    rating: 4.7,
    students: 1100,
    price: "$179",
    description: "Excel in IELTS writing tasks with proven strategies and practice exercises.",
    topics: ["Task 1 Analysis", "Task 2 Essays", "Grammar", "Vocabulary", "Time Management"],
    nextStart: "Jan 10, 2025",
    image: "/ielts-writing-course.jpg",
    category: "Test Prep",
    isLive: true,
    language: "English",
    certificate: true,
  },
  {
    id: 4,
    title: "GRE Quantitative Reasoning",
    instructor: "Prof. David Kim",
    duration: "10 weeks",
    level: "Advanced",
    rating: 4.6,
    students: 750,
    price: "$299",
    description: "Master GRE quantitative concepts and problem-solving techniques.",
    topics: ["Arithmetic", "Algebra", "Geometry", "Data Analysis", "Word Problems"],
    nextStart: "Jan 15, 2025",
    image: "/gre-quant-course.jpg",
    category: "Test Prep",
    isLive: true,
    language: "English",
    certificate: true,
  },
  {
    id: 5,
    title: "GMAT Verbal Mastery",
    instructor: "Dr. Lisa Rodriguez",
    duration: "7 weeks",
    level: "Advanced",
    rating: 4.8,
    students: 920,
    price: "$249",
    description: "Excel in GMAT verbal reasoning with comprehensive strategies.",
    topics: ["Reading Comprehension", "Critical Reasoning", "Sentence Correction", "Logic", "Strategy"],
    nextStart: "Feb 1, 2025",
    image: "/gmat-verbal-course.jpg",
    category: "Test Prep",
    isLive: true,
    language: "English",
    certificate: true,
  },

  // Writing and Communication
  {
    id: 6,
    title: "University Essay Writing",
    instructor: "Dr. Emily Rodriguez",
    duration: "10 weeks",
    level: "Advanced",
    rating: 4.7,
    students: 2100,
    price: "$299",
    description: "Craft compelling personal statements and essays that stand out to admissions officers.",
    topics: ["Personal Statement", "Supplemental Essays", "Storytelling", "Editing", "Revision"],
    nextStart: "Jan 5, 2025",
    image: "/essay-writing-course.jpg",
    category: "Writing",
    isLive: true,
    language: "English",
    certificate: true,
  },
  {
    id: 7,
    title: "Academic Writing Skills",
    instructor: "Prof. James Wilson",
    duration: "6 weeks",
    level: "Intermediate",
    rating: 4.5,
    students: 1800,
    price: "$199",
    description: "Develop strong academic writing skills for university success.",
    topics: ["Research Methods", "Citation", "Structure", "Argumentation", "Style"],
    nextStart: "Dec 30, 2024",
    image: "/academic-writing-course.jpg",
    category: "Writing",
    isLive: false,
    language: "English",
    certificate: true,
  },
  {
    id: 8,
    title: "Creative Writing Workshop",
    instructor: "Ms. Anna Martinez",
    duration: "8 weeks",
    level: "All Levels",
    rating: 4.6,
    students: 650,
    price: "$179",
    description: "Unleash your creativity and develop your unique writing voice.",
    topics: ["Fiction Writing", "Poetry", "Character Development", "Plot Structure", "Dialogue"],
    nextStart: "Jan 20, 2025",
    image: "/creative-writing-course.jpg",
    category: "Writing",
    isLive: true,
    language: "English",
    certificate: true,
  },

  // Interview and Communication
  {
    id: 9,
    title: "Interview Preparation",
    instructor: "Ms. Lisa Wang",
    duration: "4 weeks",
    level: "All Levels",
    rating: 4.6,
    students: 750,
    price: "$99",
    description: "Prepare for university interviews with mock sessions and expert tips.",
    topics: ["Interview Techniques", "Common Questions", "Body Language", "Confidence Building", "Practice Sessions"],
    nextStart: "Dec 25, 2024",
    image: "/interview-prep-course.jpg",
    category: "Interview",
    isLive: true,
    language: "English",
    certificate: true,
  },
  {
    id: 10,
    title: "Public Speaking Mastery",
    instructor: "Dr. Robert Taylor",
    duration: "6 weeks",
    level: "All Levels",
    rating: 4.8,
    students: 1200,
    price: "$199",
    description: "Overcome speaking anxiety and deliver powerful presentations.",
    topics: ["Presentation Skills", "Voice Training", "Body Language", "Audience Engagement", "Confidence"],
    nextStart: "Jan 8, 2025",
    image: "/public-speaking-course.jpg",
    category: "Communication",
    isLive: true,
    language: "English",
    certificate: true,
  },

  // Language Learning
  {
    id: 11,
    title: "English Conversation Practice",
    instructor: "Prof. Maria Santos",
    duration: "12 weeks",
    level: "Beginner",
    rating: 4.7,
    students: 2000,
    price: "$149",
    description: "Improve your English speaking skills through interactive conversations.",
    topics: ["Daily Conversations", "Pronunciation", "Vocabulary", "Grammar", "Cultural Context"],
    nextStart: "Dec 18, 2024",
    image: "/english-conversation-course.jpg",
    category: "Language",
    isLive: true,
    language: "English",
    certificate: true,
  },
  {
    id: 12,
    title: "Spanish for Beginners",
    instructor: "Prof. Carlos Mendez",
    duration: "16 weeks",
    level: "Beginner",
    rating: 4.6,
    students: 850,
    price: "$199",
    description: "Learn Spanish from scratch with immersive lessons and practice.",
    topics: ["Basic Grammar", "Vocabulary", "Pronunciation", "Conversation", "Culture"],
    nextStart: "Jan 12, 2025",
    image: "/spanish-beginner-course.jpg",
    category: "Language",
    isLive: true,
    language: "Spanish",
    certificate: true,
  },

  // Technology and Skills
  {
    id: 13,
    title: "Digital Literacy for Students",
    instructor: "Mr. Alex Chen",
    duration: "4 weeks",
    level: "All Levels",
    rating: 4.5,
    students: 1500,
    price: "$99",
    description: "Master essential digital tools and skills for academic success.",
    topics: ["Research Tools", "Document Management", "Online Collaboration", "Digital Ethics", "Productivity"],
    nextStart: "Dec 22, 2024",
    image: "/digital-literacy-course.jpg",
    category: "Technology",
    isLive: false,
    language: "English",
    certificate: true,
  },
  {
    id: 14,
    title: "Data Analysis Fundamentals",
    instructor: "Dr. Jennifer Liu",
    duration: "8 weeks",
    level: "Intermediate",
    rating: 4.7,
    students: 980,
    price: "$249",
    description: "Learn data analysis skills using Excel and basic statistical methods.",
    topics: ["Excel Functions", "Data Visualization", "Statistics", "Charts", "Analysis"],
    nextStart: "Feb 5, 2025",
    image: "/data-analysis-course.jpg",
    category: "Technology",
    isLive: true,
    language: "English",
    certificate: true,
  },

  // Study Skills and Productivity
  {
    id: 15,
    title: "Study Skills Mastery",
    instructor: "Dr. Patricia Brown",
    duration: "5 weeks",
    level: "All Levels",
    rating: 4.8,
    students: 2200,
    price: "$149",
    description: "Develop effective study habits and learning strategies for academic success.",
    topics: ["Time Management", "Note Taking", "Memory Techniques", "Test Preparation", "Focus"],
    nextStart: "Jan 3, 2025",
    image: "/study-skills-course.jpg",
    category: "Study Skills",
    isLive: true,
    language: "English",
    certificate: true,
  },
  {
    id: 16,
    title: "Time Management for Students",
    instructor: "Ms. Rachel Green",
    duration: "3 weeks",
    level: "All Levels",
    rating: 4.6,
    students: 1800,
    price: "$79",
    description: "Master time management techniques to balance studies and life effectively.",
    topics: ["Planning", "Prioritization", "Goal Setting", "Productivity", "Work-Life Balance"],
    nextStart: "Dec 28, 2024",
    image: "/time-management-course.jpg",
    category: "Study Skills",
    isLive: false,
    language: "English",
    certificate: true,
  },

  // Career Development
  {
    id: 17,
    title: "Resume Writing Workshop",
    instructor: "Mr. Kevin Park",
    duration: "3 weeks",
    level: "All Levels",
    rating: 4.7,
    students: 1600,
    price: "$129",
    description: "Create a compelling resume that gets you noticed by employers.",
    topics: ["Resume Structure", "Keywords", "Achievements", "Formatting", "ATS Optimization"],
    nextStart: "Jan 18, 2025",
    image: "/resume-writing-course.jpg",
    category: "Career",
    isLive: true,
    language: "English",
    certificate: true,
  },
  {
    id: 18,
    title: "LinkedIn Profile Optimization",
    instructor: "Ms. Sarah Davis",
    duration: "2 weeks",
    level: "All Levels",
    rating: 4.5,
    students: 1200,
    price: "$89",
    description: "Build a professional LinkedIn presence that attracts opportunities.",
    topics: ["Profile Setup", "Networking", "Content Strategy", "Professional Branding", "Job Search"],
    nextStart: "Feb 10, 2025",
    image: "/linkedin-course.jpg",
    category: "Career",
    isLive: false,
    language: "English",
    certificate: true,
  },

  // Specialized Skills
  {
    id: 19,
    title: "Research Methodology",
    instructor: "Dr. Thomas Anderson",
    duration: "9 weeks",
    level: "Advanced",
    rating: 4.8,
    students: 750,
    price: "$299",
    description: "Master research methods and academic writing for graduate studies.",
    topics: ["Research Design", "Data Collection", "Analysis", "Ethics", "Publication"],
    nextStart: "Jan 25, 2025",
    image: "/research-methodology-course.jpg",
    category: "Research",
    isLive: true,
    language: "English",
    certificate: true,
  },
  {
    id: 20,
    title: "Critical Thinking Skills",
    instructor: "Prof. Amanda White",
    duration: "6 weeks",
    level: "Intermediate",
    rating: 4.6,
    students: 1400,
    price: "$179",
    description: "Develop critical thinking skills essential for academic and professional success.",
    topics: ["Logic", "Argumentation", "Problem Solving", "Analysis", "Evaluation"],
    nextStart: "Feb 15, 2025",
    image: "/critical-thinking-course.jpg",
    category: "Skills",
    isLive: true,
    language: "English",
    certificate: true,
  },
];

export const categories = [
  { name: "All Trainings", count: trainings.length },
  { name: "Test Prep", count: trainings.filter(t => t.category === "Test Prep").length },
  { name: "Writing", count: trainings.filter(t => t.category === "Writing").length },
  { name: "Interview", count: trainings.filter(t => t.category === "Interview").length },
  { name: "Communication", count: trainings.filter(t => t.category === "Communication").length },
  { name: "Language", count: trainings.filter(t => t.category === "Language").length },
  { name: "Technology", count: trainings.filter(t => t.category === "Technology").length },
  { name: "Study Skills", count: trainings.filter(t => t.category === "Study Skills").length },
  { name: "Career", count: trainings.filter(t => t.category === "Career").length },
  { name: "Research", count: trainings.filter(t => t.category === "Research").length },
  { name: "Skills", count: trainings.filter(t => t.category === "Skills").length },
];