export const universities = [
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    location: "Cambridge, MA, USA",
    ranking: 1,
    rating: 4.9,
    tuition: "$57,986/year",
    acceptance: "6.7%",
    image: "/mit-campus-aerial.png",
    programs: ["Computer Science", "Engineering", "Physics", "Mathematics"],
    deadline: "Jan 1, 2025",
  },
  {
    id: "stanford",
    name: "Stanford University",
    location: "Stanford, CA, USA",
    ranking: 2,
    rating: 4.8,
    tuition: "$61,731/year",
    acceptance: "4.3%",
    image: "/stanford-campus.jpg",
    programs: ["Computer Science", "Business", "Medicine", "Engineering"],
    deadline: "Jan 2, 2025",
  },
  {
    id: "harvard",
    name: "Harvard University",
    location: "Cambridge, MA, USA",
    ranking: 3,
    rating: 4.9,
    tuition: "$57,261/year",
    acceptance: "3.4%",
    image: "/harvard-campus.jpg",
    programs: ["Liberal Arts", "Medicine", "Law", "Business"],
    deadline: "Jan 1, 2025",
  },
  {
    id: "oxford",
    name: "University of Oxford",
    location: "Oxford, UK",
    ranking: 4,
    rating: 4.7,
    tuition: "£26,770/year",
    acceptance: "17.5%",
    image: "/oxford-university-campus.jpg",
    programs: ["Philosophy", "Literature", "Medicine", "Law"],
    deadline: "Oct 15, 2024",
  },
];